export BUILT_PRODUCTS_DIR="/Users/danielboning/Library/Developer/Xcode/DerivedData/Build/Products/Release-iphonesimulator"
export CURRENT_ARCH="x86_64"
export OBJECT_FILE_DIR_normal="/Users/danielboning/Library/Developer/Xcode/DerivedData/Build/Intermediates/tumitfahrer.build/Release-iphonesimulator/mitfahrer-app.build/Objects-normal"
export OBJROOT="/Users/danielboning/Library/Developer/Xcode/DerivedData/Build/Intermediates"
export SRCROOT="/Users/danielboning/Workspace/TUMitfahrer/tumitfahrer-ios"
